# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

flutter_application_path = '/Users/macshop/mhealth/flutter_module_dlvn'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')


target 'ios_pj' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios_pj
  install_all_flutter_pods(flutter_application_path)
  
  post_install do |installer|
    flutter_post_install(installer) if defined?(flutter_post_install)
  end

  target 'ios_pjTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ios_pjUITests' do
    # Pods for testing
  end

end
